apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: devops-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dashboard-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "events"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets", "daemonsets"]
  verbs: ["get", "list", "watch", "patch", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments/scale", "statefulsets/scale", "replicasets/scale"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-cluster-binding
subjects:
- kind: ServiceAccount
  name: dashboard-sa
  namespace: devops-demo
roleRef:
  kind: ClusterRole
  name: dashboard-cluster-role
  apiGroup: rbac.authorization.k8s.io
